import os
from typing import List, Dict

class FileManager:
    def __init__(self, base_dir: str = "docs", topic: str = None):
        self.base_dir = base_dir
        if topic:
            self.topic_dir = os.path.join(base_dir, topic)
        else:
            self.topic_dir = base_dir
        if not os.path.exists(self.topic_dir):
            os.makedirs(self.topic_dir)

    def save_subtopic(self, filename: str, content: str):
        """
        Saves a subtopic's Markdown content to a file.
        """
        safe_filename = "".join([c if c.isalnum() or c in " _-" else "_" for c in filename]).strip()
        safe_filename = safe_filename.replace(" ", "_").lower() + ".md"
        
        file_path = os.path.join(self.topic_dir, safe_filename)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        return safe_filename

    def generate_index_page(self, topic: str, subtopics: List[Dict[str, str]], filenames: List[str]):
        """
        Generates a main index page (README.md) listing all subtopics.
        """
        index_md = f"# {topic} Documentation\n\n"
        index_md += "Welcome to the comprehensive guide on **" + topic + "**. This documentation is structured to build your understanding from basic to advanced concepts.\n\n"
        index_md += "## Table of Contents\n\n"
        
        for i, subtopic in enumerate(subtopics):
            title = subtopic.get("title")
            filename = filenames[i]
            index_md += f"{i+1}. [{title}]({filename})\n"
            
        index_md += "\n---\n"
        index_md += "*Generated by the Multi-Agent Documentation System.*\n"
        
        readme_path = os.path.join(self.topic_dir, "README.md")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(index_md)
        
        return "README.md"

    def save_references(self, references_content: str):
        """
        Saves the references section to a separate file.
        """
        file_path = os.path.join(self.base_dir, "references.md")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(references_content)
        return "references.md"
